// <auto-generated />
using KalkulatorWaluty.BazaDanych;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KalkulatorWaluty.Migrations
{
    [DbContext(typeof(KalkulatorWalutContext))]
    [Migration("20210206110500_Waluty")]
    partial class Waluty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("KalkulatorWaluty.BazaDanych.Waluta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrzelicznikDoDolara")
                        .HasColumnType("float");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Waluty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Dolar",
                            PrzelicznikDoDolara = 1.0,
                            Symbol = "USD"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Złoty",
                            PrzelicznikDoDolara = 0.26629999999999998,
                            Symbol = "PLN"
                        },
                        new
                        {
                            Id = 3,
                            Nazwa = "Euro",
                            PrzelicznikDoDolara = 1.1977,
                            Symbol = "EUR"
                        },
                        new
                        {
                            Id = 4,
                            Nazwa = "Frank Szwajcarski",
                            PrzelicznikDoDolara = 1.1074999999999999,
                            Symbol = "CHF"
                        },
                        new
                        {
                            Id = 5,
                            Nazwa = "Funt Szterling",
                            PrzelicznikDoDolara = 1.369,
                            Symbol = "GBP"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
